# -*- coding: cp936 -*-


MEAL_ALLOWANCE_WORKBOOK_NAME = u"饭补.xlsx"

MEAL_ALLOWANCE_TITILE_CELL = "A1"

MEAL_ALLOWANCE_AUTHOR_TITILE_CELL = "A2"
MEAL_ALLOWANCE_AUTHOR_TITILE = u"制表人： "

MEAL_ALLOWANCE_AUTHOR_CELL = "B2"
MEAL_ALLOWANCE_AUTHOR = u"陆笑一"

MEAL_ALLOWANCE_DATE_TITILE = u"制表日期： "

FIRST_RECORD_ROW = 3

SN_COL              = 1
ID_COL              = 2
NAME_COL            = 3
WORKDAY_COL         = 4
EVECTION_COL        = 5
ANNUAL_LEAVE_COL    = 6
SICK_LEAVE_COL      = 7
MATERNITY_LEAVE_COL = 8
CASUAL_LEAVE_COL    = 9
MARRIAGE_LEAVE_COL  = 10
FUNERAL_LEAVE_COL   = 11
OTHER_LEAVE_COL     = 12
ATTEND_DAY_COL      = 13
MEAL_ALLOWANCE_COL  = 14
REMARK_COL          = 15

MEAL_ALLOWANCE_AMOUNT = 40







